# config/services.yaml
parameters:
    cards_directory: "%kernel.project_dir%/public/uploads/cards"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
            - "../src/DataFixtures/" # <-- 1. AJOUTEZ CETTE LIGNE ICI

    App\Service\ImageUploadService:
        arguments:
            $uploadDir: "%cards_directory%"

    # <-- 2. SUPPRIMEZ LE BLOC App\DataFixtures\CardFixtures QUI ÉTAIT ICI

    # Tableaux Markdown
    League\CommonMark\Extension\Table\TableExtension:
        tags: ["twig.markdown.league_extension"]
