scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        server_name: HubLim
        issuer: HubLim
        template: security/2fa_form.html.twig
    email:
        enabled: true
        sender_email: noreply@hublim.bradype.fr
        sender_name: HubLim
        digits: 6
        template: security/2fa_form_email.html.twig
